version: '4.6.13'

services:
  postgres_cp:
    container_name: postgres_cp
    image: postgres:15
    env_file:
      - .local.env
    ports:
      - 5432:5432
    restart: always
    networks:
      - joosi

  redis_cp: 
    container_name: redis_cp
    image: redis
    ports:
      - 6379:6379
    networks:
      - joosi
    
volumes:
  pgdata:
networks:
  joosi: